### ISSUE TITLE
https://smartsheet-platform.github.io/api-docs/index.html hanging for weeks

### ISSUE THREAD

**Issue by sun-pgdx** [smartsheet-platform/smartsheet-python-sdk#105]
The site is generally unusable because it just hangs.
Just wanted to get this on our radar.

**Comment by sun-pgdx** [comment]
FYI - This happens in Chrome.
Ubuntu 18.04
Chrome Version 66.0.3359.139 (Official Build) (64-bit)

macOS High Sierra version 10.13.4
Chrome Version 66.0.3359.181 (Official Build) (64-bit)

**Comment by timwellswa** [comment]
Are you doing anything special, or just loading the main docs page?

**Comment by sun-pgdx** [comment]
Nothing special.
Just loading the main docs page.

**Comment by kfansler** [comment]
Can you provide some context please? For instance, how long have you had this problem? Have you used the docs before and the problem is new? Are you using the docs for the first time today? Do you perhaps use a Chrome plug-in that blocks unknown URLs? Sorry for so many questions, but I can't repro what you're seeing, so not sure how to help without more detail.
