### ISSUE TITLE
get_row returns null for createdAt and modifiedAt values

### ISSUE THREAD

**Issue by daveskull81** [smartsheet-platform/smartsheet-python-sdk#48]
```
row = smartsheet.Sheets.get_row(SHEET_ID,ROW_ID)
print(row)
```

In response the createdAt and modifiedAt values are null instead of containing date/time values.

**Comment by bradrjones** [comment]
Reply from Smartsheet Support:

Thanks for reaching out. At this time there is a bug in the Python SDK where the modifiedAt and createdAt parameters return null values. As you have seen, direct calls to the API do return this value correctly. I would suggest making calls to the API directly rather than using the SDK.

So... they know about it.

**Comment by timwellswa** [comment]
fixed by adding parsing to date strings returned through API
